base:
  role: "full_node"
  data_dir: "/mnt/f/aptos/data"
  waypoint:
    from_file: "/mnt/f/aptos/genesis/waypoint.txt"

execution:
  genesis_file_location: "/mnt/f/aptos/genesis/genesis.blob"

full_node_networks:
  - discovery_method: "onchain"
    listen_address: "/ip4/0.0.0.0/tcp/6182"
    max_inbound_connections: 0
    mutual_authentication: true

api:
  enabled: true
  address: "127.0.0.1:44444"

storage:
  enable_indexer: true
  storage_pruner_config:
    ledger_pruner_config:
      enable: false

indexer:
  enabled: true
  check_chain_id: true
  emit_every: 0
  batch_size: 512
  postgres_uri: "postgres://postgres@localhost:5432/postgres"
  processor: "coin_processor"
  fetch_tasks: 8
  processor_tasks: 8
